cloudfoundry/loggregator-agent-release

jobs/loggregator_agent/spec
jobs/loggregator_agent/templates/bpm.yml.erb
jobs/loggregator_agent_windows/monit
jobs/loggregator_agent_windows/spec

We would like to have the ability to override the use of the bosh-dns query language setting of the ROUTER_ADDR and ROUTER_AZ_URL.
This is so we can work with the loggregator agent when we have a different DNS provider than bosh-dns.
I'm not sure if the loggregator_agent_windows changes are good because this is not something we use.  Please feel free to give us the feedback there if it needs to be updated.

Enable override of the doppler addresses of the loggregator agent

---

jobs/loggr-syslog-agent-windows/monit
jobs/loggr-syslog-agent-windows/spec
jobs/loggr-syslog-agent/spec
jobs/loggr-syslog-agent/templates/bpm.yml.erb

The loggr_syslog_agent only sets the binding cache url through bosh-dns addresses.   We need the ability to set this using a bosh-dns alias which will be more consistent with the rest of the platform and enable use cases where we do not want to be limited by the bosh-dns addresses returned.
This is consistent with other compoents such as loggregator_agent which allows the override of the doppler addresses.

Allow for override of binding cache address from bosh-dns

---

jobs/loggr-syslog-binding-cache/spec
jobs/loggr-syslog-binding-cache/templates/bpm.yml.erb

Need to be able to specify a service endpoint rather than relying on bosh links.  Similar to other PRs I have submitted regarding possibility to override URLs.

Allow override of cloud_controller API url

---

jobs/loggr-udp-forwarder/spec
jobs/loggr-udp-forwarder/templates/bpm.yml.erb

* fixes this issue: https://github.com/cloudfoundry/loggregator-agent-release/issues/44
* [#178056975](https://www.pivotaltracker.com/story/show/178056975)
1. Deploy with the udp-forwarder on any VM
1. ssh onto that VM
1. run `netstat -tlpn | grep udp-forwarder`
1. see that ports 14829 and 14830 are being used
1. look at stderr.log and see that the debug endpoint is running on 14830.
1. run `monit restart loggr-udp-forwarder`
1. run `netstat -tlpn | grep udp-forwarder`
1. see that ports 14829 and 14830 are STILL being used
1. look at stderr.log and see that the debug endpoint is STILL running on 14830.
1. 🎉🎉🎉

make debug port configurable

---

jobs/loggr-system-metrics-agent/spec
jobs/loggr-system-metrics-agent/templates/ctl.erb

**Steps to reproduce**
1. Deploy with the loggr-system-metrics-agent on any VM
2. ssh onto that VM
3. run netstat -tlpn | grep system-metric
4. see that ports 9100 and 14922
6. run monit restart lloggr-system-metrics-agent
7. run netstat -tlpn | grep system-metric
8. see that ports 9100 and 14922 are STILL being used
🎉🎉🎉

Make debug port configurable for loggr-system-metrics-agent

---

src/pkg/scraper/config_provider.go
src/pkg/scraper/config_provider_test.go

allows optionally configuring prom scraping for releases
Signed-off-by: Matthew Kocher <mkocher@vmware.com>

skip config files with invalid ports

---

src/pkg/ingress/bindings/blacklist_ranges.go
src/pkg/ingress/bindings/blacklist_ranges_test.go
src/pkg/ingress/bindings/filtered_binding_fetcher.go
src/pkg/ingress/bindings/filtered_binding_fetcher_test.go

- if logic for invalid app drains emitting logs exists, it should
- exist in the binding cache, not every single syslog-agent
- be less noisy
- go to the app log stream rather then operator logs
- fixed certain drains to not be marked as invalid (aka, drains processed by other components)
Signed-off-by: Matthew Kocher <mkocher@vmware.com>

Remove noisy logging for invalid app drains

---

src/cmd/agent/app/app_v2.go
src/cmd/forwarder-agent/app/forwarder_agent.go
src/cmd/forwarder-agent/app/forwarder_agent_test.go
src/cmd/syslog-agent/app/syslog_agent.go
src/pkg/egress/syslog/tcp.go

- make sure we can handle batches of max sized envelopes from diego
max size is 61440
we ran this against a actual environment

max message size changes

---

src/cmd/prom-scraper/app/prom_scraper.go
src/cmd/prom-scraper/app/prom_scraper_test.go

Prom scraper logs a recovery message when a scrape succeeds after a failure occurs.
Supersedes #73.

Feat: prom scraper log on recovery

---

docs/prom-scraper.md
jobs/prom_scraper/spec
jobs/prom_scraper/templates/bpm.yml.erb
src/cmd/prom-scraper/app/prom_scraper.go
src/cmd/prom-scraper/app/prom_scraper_test.go
src/pkg/scraper/config_provider.go

- services and externally deployed offerings might wish to expose metrics endpoints with certs that are
more internet friendly then the "metrics only prom scraper certs" or fit in with their own cert ecosystem
this allows overriding the default loggregator certs and ca used when prom scraping a job.

Add option for custom certs to prom scraper

---

src/pkg/egress/diode_writer_test.go
src/pkg/ingress/v1/network_reader_test.go
src/pkg/timeoutwaitgroup/timeout_wait_group_test.go

Ginkgo 2.0 is GA. Some of the tests are raising warnings about new features, improvements, and a small handful of breaking changes. This pull request addresses the following warnings:
- GinkgoParallelNode is deprecated and will be removed in Ginkgo V2.  Please use GinkgoParallelProcess instead. Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#renamed-ginkgoparallelnode
- You are passing a Done channel to a test node to test asynchronous behavior.  This is deprecated in Ginkgo V2.  Your test will run synchronously and the timeout will be ignored. Learn more at: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-async-testing
- Using `time.Since(startTime)` instead of `time.Now().Sub(startTime)`
If you have any questions, or want to get …

Futureproofing async ginkgo testing

---

src/cmd/syslog-agent/app/syslog_agent_test.go
src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go
src/cmd/udp-forwarder/app/app_suite_test.go
src/pkg/egress/syslog/writer_factory.go
src/pkg/egress/syslog/writer_factory_test.go

Add drain scope and url tags to egress metric in order to enable better tracking of syslog messages per drain. As perviously discussed on [slack](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1656599906962669?thread_ts=1654252617.471169&cid=CUW93AF3M) , we added tags to the syslog egress drain metric.

Add drain scope and url tags to syslog egress metrics

---

.github/workflows/go.yml

Make go workflow run properly against PRs to `v6.x`.

CI: fix go workflow target for version branch

---

.github/dependabot.yml

Makes it easier to distinguish between dependabot PRs for different target branches.

CI: add branch-specific labels to dependabot PRs

---

src/pkg/egress/syslog/writer_factory.go
src/pkg/egress/syslog/writer_factory_test.go

Anonymizes URL emitted in syslog drain logs and syslog drain metrics.

Fix: anonymize URL in syslog drain logs and metrics

---

src/pkg/egress/syslog/syslog_connector.go
src/pkg/egress/syslog/syslog_connector_test.go

As discussed in #203 we've seen when an app has multiple syslog drains or one syslog drain was bound to multiple apps in was hard to tell which syslog drain for which app has log drops. We've adjusted the error message which is injected to the applications log, so that this becomes clear.
Now the error messages looks as following:
```
2023-01-26T17:08:28.31+0000 [LGR/LGR] ERR 10000 messages lost for application <app-guid> in user provided syslog drain with url <anonymized-syslog-drain-url>
```
We've adjusted the unit test and did integration test, deployed the new version of the syslog-agent and checked the app logs for an application which produces many logs/s. We've also tested with a syslog url like `https://user:pass@example.com?p1=v1` and in the logs we only saw the "base url", …

Add app-id and drain url in the error message

---

.github/workflows/go.yml

Increases timeout for `golangci-lint run` from 1m (default) to 5m.

CI: fix Go / Lint workflow

---

jobs/loggr-syslog-binding-cache/spec
jobs/loggr-syslog-binding-cache/templates/bpm.yml.erb
src/cmd/syslog-agent/app/syslog_agent.go
src/cmd/syslog-binding-cache/app/config.go
src/cmd/syslog-binding-cache/app/syslog_binding_cache.go
src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go
src/pkg/plumbing/tls.go

This PR makes keepalive connection between cloud_controller_ng and syslog-binding-cache configurable. Disabling keepalive probes will result in different VMs being called when polling the cloud controller for syslog-binding information.

Make keepalives for api polling configurable

---

src/pkg/egress/syslog/filtering_drain_writer.go
src/pkg/egress/syslog/filtering_drain_writer_test.go
src/pkg/egress/syslog/syslog_connector.go
src/pkg/ingress/bindings/aggregate_fetcher.go
src/pkg/ingress/bindings/aggregate_fetcher_test.go
src/pkg/ingress/bindings/binding_config.go
src/pkg/ingress/bindings/binding_config_test.go
src/pkg/ingress/bindings/binding_fetcher.go
src/pkg/ingress/bindings/binding_fetcher_test.go

* Unify where parsing of binding parameters happen
* Unify the types of drains that exist. Allow users to egress timers, allow aggregate drains to egress only logs
* Update the name of the omit-metadata flag. 

Update binding params

---

jobs/otel-collector-windows/spec
jobs/otel-collector/spec

- Switching the default from the standard OTel Collector port to instead use port 3462.
- The new default port is a natural extension of the existing loggregator agent suite port range.

OTel Collector gRPC listens on port 3462

---

jobs/otel-collector/spec

we've reclaimed 9100 from system-metrics-agent to use as our ingress port. It will be reserved for us on tcp-router already, which is nice.
3462 was not going to be reserved for use on tcp-router

change default otel-collector grpc port

---

jobs/otel-collector-windows/templates/config.yml.erb
jobs/otel-collector/templates/config.yml.erb

- Error when rendering OTel Collector config if the component identifier for metric exporters contains '/cf-internal'.
- Reserving this name prefix for potential later use.
Sample deployment time failure:
```
Task 83 | 02:33:18 | Error: Unable to render instance groups for deployment. Errors are:
- Unable to render jobs for instance group 'windows2019-cell'. Errors are:
- Unable to render templates for job 'otel-collector-windows'. Errors are:
- Error filling in template 'config.yml.erb' (line 3: Metric exporters cannot be defined under cf-internal namespace)
```

Reserve metric exporter name prefix

---

jobs/otel-collector-windows/templates/config.yml.erb
jobs/otel-collector/templates/config.yml.erb

Allow metric exporters to be provided as a string (or as a hash as previously).
Manually deployed with exporters defined as strings and hashes and observed successful deployment.

Allow metric exporters to be provided as a string

---

packages/otel-collector-windows/packaging

- PR #360 changed the otel-collector-windows packaging script to use Windows-style backslashes as path delimiters
- This isn't actually desirable everywhere because the first line of the packaging script exists to prevent an error when exporting a BOSH release and attempting to compile this Windows package on a Linux instance
Fixes:
```
.exiter.ps1: No such file or directory
```

Fix otel-collector-windows packaging script

---

jobs/otel-collector-windows/spec
jobs/otel-collector-windows/templates/config.yml.erb
jobs/otel-collector-windows/templates/prom_scraper_config.yml.erb
jobs/otel-collector/spec
jobs/otel-collector/templates/config.yml.erb
jobs/otel-collector/templates/prom_scraper_config.yml.erb

Configure a prometheus endpoint which serves metrics about the otel-collector itself. Also adds a prom_scraper_config so promscraper scrapes the metrics.

add otel collector service telemetry metrics

---

src/cmd/forwarder-agent/app/forwarder_agent_test.go
src/cmd/forwarder-agent/app/otelcolclient/otelcolclient.go
src/cmd/forwarder-agent/app/otelcolclient/otelcolclient_test.go

Our current method of converting Timer envelopes to single event Histograms to send to an OTel Collector is not ideal. While we think more deeply about how to do this conversion, we want to rip out the conversion code so no one starts depending on this format.

chore(cmd/forwarder-agent): do not forward Timers

---

src/otel-collector/config.yaml
src/otel-collector/main.go

Set the version of our OTel Collector distribution to 0.1.0 to indicate that it is experimental.

chore(otel-collector): use non-GA version

---

src/cmd/forwarder-agent/app/app_suite_test.go

- In #89 we increased the gRPC MaxRecvMsgSize for the Forwarder Agent and the downstream Loggregator Agent and Syslog Agent
- Also set this on the test ingress server in the Forwarder Agent tests to avoid flakes

Bump max message size on FA test ingress server

---

src/cmd/forwarder-agent/app/app_suite_test.go
src/cmd/forwarder-agent/app/forwarder_agent.go
src/cmd/forwarder-agent/app/forwarder_agent_test.go

Emit a metric, `egress_expired_total`, per Forwarder Agent egress destination to track the number of envelopes dropped from that designation's diode.

Feat(Forwarder Agent): Add a counter to track drops from egress diodes

---

jobs/loggr-syslog-agent/spec
jobs/loggr-syslog-agent/templates/bpm.yml.erb
src/cmd/syslog-agent/app/config.go
src/cmd/syslog-agent/app/syslog_agent.go
src/pkg/ingress/bindings/filtered_binding_fetcher.go
src/pkg/ingress/bindings/filtered_binding_fetcher_test.go

- In 62f65b38 we added log messages for invalid syslog drains to the syslog agent.
- Allow operators to suppress these messages if they would prefer not to have them present in the syslog agent logs.

Operators can suppress warnings for invalid drains

---

jobs/loggr-syslog-agent-windows/monit
jobs/loggr-syslog-agent-windows/spec

In #422 we made warnings for invalid syslog drains configurable but neglected to add the same property to the loggr-syslog-agent-windows job.

Operators can suppress warnings for invalid drains (Windows)

---

src/pkg/otelcolclient/otelcolclient.go
src/pkg/otelcolclient/otelcolclient_test.go

- Metrics that were received initially as v1 metrics include a __v1_type tag to indicate the type of v1 metric that was emitted.
- This causes issues for the prometheus exporter as: 'Label names beginning with __ (two "_") are reserved for internal use.' https://prometheus.io/docs/concepts/data_model/
- Remove the __v1_type tag during the conversion so that these metrics will be acceptable to prometheus exporters.
Fixes:
```
"__v1_type" is not a valid label name for metric
```

Remove __v1_type tag when forwarding metrics to otel collector

---

src/pkg/otelcolclient/otelcolclient.go
src/pkg/otelcolclient/otelcolclient_test.go

Sums must be declared as monotonic in order to be represented in prometheus as counters.
Note that this causes the otel collector to rename metrics when using the prometheus exporter. Counters have `_total` appended to the name.
There are cases where loggregator counters aren't monotonic, in particular when counters are emitted only as deltas (V1) and the counter totals are reset in the Forwarder Agent. In this case we mark the otel sum as not monotonic and it will be represented as a gauge when using the prometheus exporter.

Specify that counters are monotonic

---

jobs/loggregator_agent/templates/pre-start.erb
jobs/loggregator_agent_windows/templates/pre-start.ps1.erb

Don't register loggregator agent with forwarder agent or prom scraper when the loggregator agent is not enabled.

Don't register loggregator agent when not enabled

---

packages/binding-cache/packaging
packages/binding-cache/spec
packages/forwarder-agent-windows/packaging
packages/forwarder-agent-windows/spec
packages/forwarder-agent/packaging
packages/forwarder-agent/spec
packages/golang-1.20-linux/spec.lock
packages/golang-1.20-windows/spec.lock
packages/loggregator_agent/packaging
packages/loggregator_agent/spec
packages/loggregator_agent_windows/packaging
packages/loggregator_agent_windows/spec
packages/prom_scraper/packaging
packages/prom_scraper/spec
packages/prom_scraper_windows/packaging
packages/prom_scraper_windows/spec
packages/syslog-agent-windows/packaging
packages/syslog-agent-windows/spec
packages/syslog-agent/packaging
packages/syslog-agent/spec
packages/udp-forwarder/packaging
packages/udp-forwarder/spec
src/go.mod
src/go.sum

* Removes go1.20 packages
* Uses go1.21 packages to build the other packages
* Specify go1.21 as the go version in `src/go.mod`

Bump to go1.21

---

jobs/loggr-syslog-binding-cache/spec

This PR fixes just a very simple typo in the job specification of `loggr-syslog-binding-cache`.

Fix typo in specification of job `loggr-syslog-binding-cache`

---

.github/workflows/scripts.yml

Fixes failing scripts/unit-test GH action by using the latest patch of go1.21 instead of go1.21.0.
We were seeing errors like:
```
Failed to compile otel-collector:
...
compile: version "go1.21.9" does not match go tool version "go1.21.0"
```

fix: Failing scripts/unit-test action

---

src/pkg/binding/poller.go

Fixes syslog-binding-cache to wait for the polling interval AFTER it has finished polling, rather than incorporating the polling time into the polling interval.

fix(syslog-binding-cache): Wait for the entire polling interval

---

src/pkg/binding/poller.go

Fixes syslog-binding-cache to wait for the polling interval AFTER it has finished polling, rather than incorporating the time it takes to poll CAPI into the polling interval.

Fix(syslog binding cache): Wait for the entire polling interval

---

src/cmd/syslog-agent/app/config.go
src/pkg/binding/poller_test.go

Address lint error and test flakiness in `PollerTest` by increasing polling interval to `100ms` to fix failing `bump-dependencies` job. Increasing the interval ensures `Poll()`  runs less frequently giving the test more time to perform the assertions before the channel is updated.

Address linting and fix unit test flakiness

---

src/internal/testhelper/port.go
src/pkg/binding/poller_test.go
src/pkg/otelcolclient/otelcolclient.go
src/pkg/plumbing/envelope_averager.go
src/pkg/simplecache/simplecache_test.go

fix flaky tests poller tests and simplecache test

---

src/pkg/otelcolclient/otelcolclient.go
src/pkg/otelcolclient/otelcolclient_test.go

Prevents ints from overflowing when being sent over otlp, as loggregator ints are unsigned and otel ints are signed. Since counters are expected to roll over we just discard the highest order bit.

fix uint to int conversion for otlp

---

jobs/loggr-forwarder-agent/spec
src/pkg/otelcolclient/otelcolclient.go

The OpenTelemetry Collector release now sets up noop pipelines to consume these signals and prevent error messages if no pipelines for the signal have been configured by the operator.

Emit all OTel signals by default

---

jobs/loggr-forwarder-agent-windows/spec

Fixes feef623ec to also add Windows support for emitting all otel signals by default.

fix: windows emits otel signals by default

---

scripts/subtests/unit-test

cherry-picked from 9d1236930563dd5d3e2b01ac4513a295eedacc81
Cherry pick test parallelism config from main.
- CI chore

disable parallel unit tests in CI

---

src/cmd/forwarder-agent/app/forwarder_agent_test.go

fix flaky forwarder-agent-test by waiting for logServer to have data

---

src/pkg/egress/syslog/https_batch.go
src/pkg/egress/syslog/https_batch_test.go
src/pkg/egress/syslog/https_test.go

This changes the way the syslog batches are triggered.
The new implementation no longer uses Timers that need to be reset and checked, it just ticks once every second per http_batch drain to send a batch at least once a second. 
The new logic is as follows:
- If there is a log present in the queue, send it at last one second later with every log from the same second.
- If there are more logs in one second than the 'batchSize' allows, send the batch immediately 
The old implementation was able to deadlock itself due to the way the time channel was reset. There are even more changes to this behaviour to be expected by the golang 1.23 update. (https://tip.golang.org/doc/go1.23#timer-changes)
-> Changed logic necessary to prevent further issues on further golang upgrades
The new …

Fix https_batch deadlock due to golang timer changes

---

scripts/subtests/lint
src/.golangci.yml
src/cmd/loggregator-agent/app/app_v1.go
src/cmd/loggregator-agent/app/app_v2.go
src/cmd/loggregator-agent/app/config.go
src/cmd/syslog-agent/app/config.go
src/cmd/syslog-agent/app/syslog_agent_mtls_test.go
src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go
src/internal/testservers/agent.go
src/pkg/egress/syslog/https.go
src/pkg/egress/syslog/tcp.go
src/pkg/egress/v1/eventwriter.go
src/pkg/ingress/v1/event_unmarshaller.go

Move to golangci-lint v2.
Changes:
* Accept [QF1004](https://staticcheck.dev/docs/checks/#QF1004): Change `Replace` to `ReplaceAll` where sensible
* Accept [QF1008](https://staticcheck.dev/docs/checks/#QF1008): Omit an embedded field
* Accept [ST1019](https://staticcheck.dev/docs/checks/#ST1019): `code.cloudfoundry.org/loggregator-agent-release/src/pkg/ingress/v2` had been imported twice
* Accept [ST1005](https://staticcheck.dev/docs/checks/#ST1005): to have nicer logs
Noteworthy changes in golangci-lint v2:
* New config format (migrated with `migrate` command)
* Default timeout is now 0 instead of 1 minute. See [here](https://github.com/golangci/golangci-lint/pull/5470/commits/d3bf353d4531c824201394821f0119a690a01519#r1968522617) for rationale. Kept ours unchanged for now.

Move to golangci v2
