jobs/prom_scraper/spec, jobs/prom_scraper/templates/bpm.yml.erb
relevant [source PR](https://github.com/cloudfoundry/loggregator-agent/pull/10)
Signed-off-by: Hunter Williams <huwilliams@pivotal.io>
cc: @hdub2 @jtuchscherer
=> change config option METRICS_URL to METRICS_URLS

jobs/prom_scraper/templates/bpm.yml.erb, jobs/prom_scraper/templates/loggregator_agent.crt.erb, jobs/prom_scraper/templates/loggregator_agent.key.erb, jobs/prom_scraper/templates/loggregator_ca.crt.erb, jobs/prom_scraper_windows/monit, jobs/prom_scraper_windows/templates/loggregator_agent.crt.erb, jobs/prom_scraper_windows/templates/loggregator_agent.key.erb, jobs/prom_scraper_windows/templates/loggregator_ca.crt.erb
Conditionally access optional loggregator link in prom_scraper erb templates
Co-authored-by: Johanna Ratliff <josmith@pivotal.io>
Fixes #16 
/cc @attack
=> Conditionally use optional loggregator link

jobs/prom_scraper/templates/bpm.yml.erb, jobs/prom_scraper/templates/loggregator_agent.crt.erb, jobs/prom_scraper/templates/loggregator_agent.key.erb, jobs/prom_scraper/templates/loggregator_ca.crt.erb, jobs/prom_scraper_windows/monit, jobs/prom_scraper_windows/templates/loggregator_agent.crt.erb, jobs/prom_scraper_windows/templates/loggregator_agent.key.erb, jobs/prom_scraper_windows/templates/loggregator_ca.crt.erb
- use else_if_link
- assign values to variables, then render to erb
Co-authored-by: Johanna Ratliff <josmith@pivotal.io>
=> Cleanup and fix prom_scraper templating

docs/prom-scraper.md
used to resolve to docs/docs/loggregato....
@MasslessParticle @kitemongerer
=> Fix broken link

src/cmd/syslog-agent/app/syslog_agent.go, src/cmd/syslog-agent/app/syslog_agent_test.go
[Relevant slack thread](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1625653234045300)
When doing some load testing with syslog drains we found that [the error produced by the syslog connector when messages get dropped](https://github.com/cloudfoundry/loggregator-agent-release/blob/e7be5bef5988218a615d0e551049cfe90779caa6/src/pkg/egress/syslog/syslog_connector.go#L134) was not being surfaced anywhere. We had a user request to be notified when their syslog drain is dropping logs so having this error visible somewhere external to the diego-cell VM would be helpful to us.
In the source code we noticed that the [default log client used by the connector is one which doesn't send logs anywhere](https://github.com/cloudfoundry/loggregator-agent-release/blob/e7be5bef5988218a615d0e551049cfe90 …
=> Add error message to syslog drain in case of dropped logs

src/pkg/egress/syslog/rfc5424.go, src/pkg/egress/syslog/rfc5424_test.go
- fix marshalling structured data with quotes, backslashes, and right brackets
Signed-off-by: Carson Long <lcarson@vmware.com>
=> migrate to go-loggregator rfc5424 package

src/pkg/clientpool/v1/pusher_fetcher_test.go, src/pkg/ingress/v2/receiver.go
Fix errors generated by `go vet ./...` in `src`:
```
pkg/ingress/v2/receiver.go:46:2: unreachable code
pkg/ingress/v2/receiver.go:64:2: unreachable code
pkg/clientpool/v1/pusher_fetcher_test.go:143:2: unreachable code
```
=> Fix errors generated by go vet

src/cmd/forwarder-agent/app/forwarder_agent.go, src/cmd/loggregator-agent/app/app_v2.go, src/cmd/prom-scraper/app/prom_scraper.go, src/cmd/syslog-agent/app/syslog_agent.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache.go, src/cmd/udp-forwarder/app/udp_forwarder.go
- determined error when working on metrics-discovery-release
=> incorrect implementation of pprof will hang server

src/cmd/forwarder-agent/app/forwarder_agent_test.go, src/cmd/loggregator-agent/app/app_v2_test.go, src/cmd/prom-scraper/app/prom_scraper_test.go, src/cmd/syslog-agent/app/syslog_agent_test.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go, src/cmd/udp-forwarder/app/udp_forwarder_test.go
Signed-off-by: Seth Boyles <sboyles@vmware.com>
=> try and improve unit test consistancy

src/cmd/forwarder-agent/app/forwarder_agent.go, src/cmd/loggregator-agent/app/app_v2.go, src/cmd/prom-scraper/app/prom_scraper.go, src/cmd/syslog-agent/app/syslog_agent.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache.go, src/cmd/udp-forwarder/app/udp_forwarder.go
Configure http servers with a ReadHeaderTimeout of 2 seconds.
=> Fix slowloris warnings

src/pkg/egress/v1/message_aggregator.go, src/pkg/egress/v2/hash_tags.go
- known insecure function. Impact should be minimal, but should help auditors/etc
=> remove the use of sha1

.github/workflows/go.yml
Signed-off-by: Rebecca Roberts <robertsre@vmware.com>
=> Add golang version file for github actions

src/pkg/clientpool/v1/conn_manager_test.go
Ensure that goroutine using mockConnector is closed before the `It` block completes or else there will be a race condition on the `mockConnector` variable from the outer `BeforeEach` block.
Put the channel write for `mockConnector.ConnectOutput.Ret2` into a case so that it doesn't write if the channel is already full. When it was the default case the goroutine could block there, preventing the goroutine from closing for up to 60 seconds.
=> Fix: race condition in v1 conn manager test

src/cmd/forwarder-agent/app/forwarder_agent.go
- refactor ingress client to new function, reduces size of function and readability
- also ensures that we are not using the loop variable, and thusly not retaining the reference to an old variable in the go function for logging. Meaning we don't always report the last port at the end of the log message for dropping.
Signed-off-by: Rebecca Roberts <robertsre@vmware.com>
=> Fix logs for forwarder agent drops

docs/prom-scraper.md, src/cmd/prom-scraper/app/prom_scraper.go, src/cmd/prom-scraper/app/prom_scraper_test.go
=> fix scraping with non-positive intervals to preserve non-scraping behavior

.github/dependabot.yml, .github/workflows/go.yml
Signed-off-by: Ben Fuller <benjaminf@vmware.com>
add testing for the v6.x branch. 
=> update workflows for v6.x

src/pkg/egress/syslog/rfc5424.go, src/pkg/egress/syslog/rfc5424_test.go
cf tasks emit logs with the task name in the "source_type". This can result in the procid containing characters which are not printable ascii characters. This is invalid per rfc5424
=> Sanitize ProcID in syslog messages

src/cmd/forwarder-agent/app/app_suite_test.go, src/cmd/forwarder-agent/app/forwarder_agent.go, src/cmd/forwarder-agent/app/forwarder_agent_test.go, src/cmd/prom-scraper/app/prom_scraper_test.go, src/cmd/syslog-agent/app/syslog_agent.go, src/cmd/syslog-agent/app/syslog_agent_mtls_test.go, src/cmd/syslog-agent/app/syslog_agent_test.go, src/cmd/syslog-binding-cache/app/app_suite_test.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go, src/cmd/udp-forwarder/app/udp_forwarder.go, src/cmd/udp-forwarder/app/udp_forwarder_test.go, src/pkg/ingress/v2/server.go
GH actions tests have been failing for a while now, and this should help some.
=> Fix: tests

docs/syslog-agent.md
Update syslog agent docs:
* Fixes title.
* Adds section noting that syslog agent anonymizes URLs.
=> Update syslog agent docs

jobs/loggr-syslog-binding-cache/spec, jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb, jobs/loggr-syslog-binding-cache/templates/bpm.yml.erb, src/cmd/syslog-agent/app/syslog_agent_mtls_test.go, src/cmd/syslog-binding-cache/app/config.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache.go, src/cmd/syslog-binding-cache/app/syslog_binding_cache_test.go, src/pkg/binding/poller.go, src/pkg/binding/store.go, src/pkg/binding/store_test.go, src/pkg/cache/client.go, src/pkg/cache/client_test.go, src/pkg/cache/handler.go, src/pkg/cache/handler_test.go, src/pkg/ingress/bindings/aggregate_fetcher.go, src/pkg/ingress/bindings/aggregate_fetcher_test.go
=> Add mtls options to aggregate drains. 

src/cmd/forwarder-agent/app/app_suite_test.go, src/cmd/forwarder-agent/app/forwarder_agent.go, src/cmd/forwarder-agent/app/forwarder_agent_test.go, src/pkg/ingress/v2/server.go
=> Fixes flakiness in tests

jobs/loggr-syslog-binding-cache/templates/aggregate_drains.yml.erb
https://github.com/cloudfoundry/capi-release/commit/cb2b55f0006435aa1a6d2e9fad5a6173e9b473fb Following cloud controller pattern
=> flatten array

src/integration_tests/agent_test.go, src/pkg/clientpool/v1/pusher_fetcher.go, src/pkg/clientpool/v2/sender_fetcher.go, src/pkg/otelcolclient/otelcolclient.go
- Replace usages of grpc.Dial with grpc.NewClient
=> Bump google.golang.org/grpc to v1.63.2 (7.x)

src/cmd/prom-scraper/app/prom_scraper_test.go
Resolve race condition in prom scraper test setup (v6.x).
(cherry picked from commit 542790cd0fd2d6a7d65f34d7490a4721ac26a1df)
=> Resolve race condition in prom scraper test setup

.github/dependabot.yml
=> remove dependabot autobump for v6

src/internal/testhelper/port.go, src/pkg/otelcolclient/otelcolclient.go, src/pkg/plumbing/envelope_averager.go
ignore linter warnings for g115 https://github.com/securego/gosec/issues/1185 
=> ignore linter warnings for G115

src/pkg/egress/syslog/https_batch.go
This change is necessary due to the current implementation details of https_batch, having no retries.
Due to the common practice on many log drain targets, to enforce a maximum keepalive times of usually 60s, this leads to predictably failing requests after 60s for http_batch requests.
To prevent this issue, the setting
`MaxConnDuration` is necessary, to prevent connections to stay alive longer than the servers keep-alive setting, leading to a predestined rejection.
=> Fix Connection keep-alive time for http batch
